[general]

import = ["alacritty-theme/themes/gruvbox_dark.toml"]

working_directory = "~/Workspace"
live_config_reload = true

[window]
dimensions = { columns = 200, lines = 120 }
padding = { x = 7, y = 7 }
dynamic_padding = true
decorations = "Buttonless"
opacity = 0.90
blur = true
startup_mode = "Windowed"
title = "Hello, world!"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments = false
option_as_alt = "None"
level = "Normal"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 13
offset = { x = 0, y = 0 }
# glyph_offset = {  }
# builtin_box_drawing = false

[colors]
primary = { foreground = "#d8d8d8", background = "#181818", dim_foreground = "#828482", bright_foreground = "None" }
cursor = { text = "CellBackground", cursor = "CellForeground" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }
search = { matches = { foreground = "#181818", background = "#ac4242" }, focused_match = { foreground = "#181818", background = "#f4bf75" } }
hints = { start = { foreground = "#181818", background = "#f4bf75" }, end = { foreground = "#181818", background = "#ac4242" } }
line_indicator = { foreground = "None", background = "None" }
footer_bar = { foreground = "#181818", background = "#d8d8d8" }
selection = { text = "CellBackground", background = "CellForeground" }
normal = { black = "#181818", red = "#ac4242", green = "#90a959", yellow = "#f4bf75", blue = "#689fb5", magenta = "#aa759f", cyan = "#75b5aa", white = "#d8d8d8" }
bright = { black = "#6b6b6b", red = "#c55555", green = "#aac474", yellow = "#feca88", blue = "#82b8c8", magenta = "#c28cb8", cyan = "#93d3c3", white = "#f8f8f8" }
dim = { black = "#0f0f0f", red = "#712b2b", green = "#5f6f3a", yellow = "#a17e4d", blue = "#456877", magenta = "#704d68", cyan = "#4d7770", white = "#8e8e8e" }
indexed_colors = []
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[bell]

[selection]

[cursor]

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }
# osc52 = "OnlyCopy"

[mouse]

[hints]


[keyboard]

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false
